<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-12T17:41:45 IST" name="Default suite" finished-at="2022-04-12T17:41:46 IST" duration-ms="490">
    <groups>
    </groups>
    <test started-at="2022-04-12T17:41:45 IST" name="Default test" finished-at="2022-04-12T17:41:46 IST" duration-ms="490">
      <class name="com.mystore.testcases.RegisterationPageTest">
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.mystore.testcases.RegisterationPageTest@1534f01b]" started-at="2022-04-12T17:41:45 IST" name="loadConfig" finished-at="2022-04-12T17:41:45 IST" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method signature="verifyRegisterationTest(java.util.HashMap)[pri:0, instance:com.mystore.testcases.RegisterationPageTest@1534f01b]" started-at="2022-04-12T17:41:45 IST" name="verifyRegisterationTest" data-provider="RegisterationSubmit" finished-at="2022-04-12T17:41:46 IST" duration-ms="475" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void com.mystore.testcases.RegisterationPageTest.verifyRegisterationTest(java.util.HashMap) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: verifyRegisterationTest([Parameter{index=0, type=java.util.HashMap, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {Email=test1997@test.com, Mobile_Number=511221234, First Name=rohan, Last Name=kumar},null,null,null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.mystore.testcases.RegisterationPageTest.verifyRegisterationTest(java.util.HashMap) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: verifyRegisterationTest([Parameter{index=0, type=java.util.HashMap, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {Email=test1997@test.com, Mobile_Number=511221234, First Name=rohan, Last Name=kumar},null,null,null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRegisterationTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.mystore.testcases.RegisterationPageTest@1534f01b]" started-at="2022-04-12T17:41:46 IST" name="afterSuite" finished-at="2022-04-12T17:41:46 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.mystore.testcases.RegisterationPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
